// AUTHENTICATION
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERRORS_SHOW_ALERT = "CLEAR_ERRORS_SHOW_ALERT";
export const GET_ERRORS_CANCEL_OFFER = "GET_ERRORS_CANCEL_OFFER";

// GET MY ORDERS HISTORY LIST
export const CLEAR_ERRORS_ORDER_CANCEL = "CLEAR_ERRORS_ORDER_CANCEL";
export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";

// GET PROFILE DATA
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

// MAKE OFFER
export const MAKE_OFFER = "MAKE_OFFER";

// CANCEL OFFER
export const CANCEL_OFFER = "CANCEL_OFFER";

// TAKE OFFER
export const TAKE_OFFER = "TAKE_OFFER";

// CLEAR ALERT
export const CLEAR_ALERT = "CLEAR_ALERT";

// RESET ERRORS
export const RESET_ERRORS = "RESET_ERRORS";

// NETWORK CODE
export const GET_STATUS_CODE = "GET_STATUS_CODE";
export const CLEAR_NETWORK_CODE = "CLEAR_NETWORK_CODE";

// GET CONFIGS DATA
export const GET_CONFIGS_DATA = "GET_CONFIGS_DATA";

// NAVIGATION STATE
export const LOGIN_PAGE = "LOGIN_PAGE";
export const SIGNUP_PAGE = "SIGNUP_PAGE";
export const MARKETPLACE_PAGE = "MARKETPLACE_PAGE";
export const SELL_PAGE = "SELL_PAGE";
export const MARKETHISTORY_PAGE = "MARKETHISTORY_PAGE";
export const MYPROFILE_PAGE = "MYPROFILE_PAGE";
export const PASSWORD_RESET_PAGE = "PASSWORD_RESET_PAGE";
export const ACCOUNT_ACTIVATION_PAGE = "ACCOUNT_ACTIVATION_PAGE";
export const RESET_PAGE = "RESET_PAGE";
export const NOT_FOUND_PAGE = "NOT_FOUND_PAGE";
export const LOGOUT_PAGE = "LOGOUT_PAGE";
export const TERMS_OF_USE_PAGE = "TERMS_OF_USE_PAGE";
export const NEWS_PAGE = "NEWS_PAGE";
export const ABOUT_US_PAGE = "ABOUT_US_PAGE";
export const REFERRAL_PAGE = "REFERRAL_PAGE";

// TOAST MESSAGES
export const REDIRECT_MESSAGE = "REDIRECT_MESSAGE";
export const NOT_FOUND_MESSAGE = "NOT_FOUND_MESSAGE";
export const CANT_TAKE_OWN_OFFER = "CANT_TAKE_OWN_OFFER";
export const NULL_TOAST = "NULL_TOAST";

// MINING ALGORITHMS SELECTOR
export const ALGOCHANGE = "ALGOCHANGE";

// FORM CONTROL
export const FORM_SUBMITTED = "FORM_SUBMITTED";
export const ENABLE_NAVIGATION = "ENABLE_NAVIGATION";

// GET OFFERS (PROFILE PAGE)
export const GET_OFFERS = "GET_OFFERS";
export const GET_OFFER_INFO = "GET_OFFER_INFO";
export const CLEAR_OFFERS = "CLEAR_OFFERS";

// LOAD ACTIVE OFFERS (MARKET MONITOR PAGE)
export const LOAD_ACTIVE_OFFERS = "LOAD_ACTIVE_OFFERS";

// LOAD TAKEN OFFERS
export const GET_SETTLEMENTS_PROFILE = "GET_SETTLEMENTS_PROFILE";
export const LOAD_TAKEN_OFFERS = "LOAD_TAKEN_OFFERS";

// ACTIVATION
export const ACTIVATION_SUCCESSFUL = "ACTIVATION_SUCCESSFUL";
export const ACTIVATION_FAILED = "ACTIVATION_FAILED";
export const RESET_ACTIVATION_STATUS = "RESET_ACTIVATION_STATUS";

// PASSWORD RESET
export const RESET_PASSWORD_SUCCESSFUL = "RESET_PASSWORD_SUCCESSFUL";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const NULL_RESET_STATUS = "NULL_RESET_STATUS";

// MINERS
export const GET_MINERS_LIST = "GET_MINERS_LIST";
export const MINERS_REMOVED = "MINERS_REMOVED";
export const RESET_MINER_STATUS = "RESET_MINER_STATUS";

// TIMEOUT ERROR HANDLING
export const TIMEOUT_ERROR = "TIMEOUT_ERROR";
export const TIMEOUT_RESET = "TIMEOUT_RESET";

// ZENDESK INTEGRATION
export const GET_ZENDESK_ARTICLES = "GET_ZENDESK_ARTICLES";
export const ZENDESK_LOAD_FAILED = "ZENDESK_LOAD_FAILED";

// GET HASHRATE INFO
export const GET_HASHRATE_INFO = "GET_HASHRATE_INFO"; 
export const CLEAR_HASHRATE_DATA = "CLEAR_HASHRATE_DATA";

// GET PAYMENT INFO
export const PAYMENT_INFO = "PAYMENT_INFO";
export const CLEAR_PAYMENT_INFO = "CLEAR_PAYMENT_INFO";

// GET BID / INVOICE INFO
export const GET_BIDS = "GET_BIDS";
export const CLEAR_BIDS = "CLEAR_BIDS";
export const GET_BID_INFO = "GET_BID_INFO";

// GET STATS
export const GET_STATS_DATA = "GET_STATS_DATA";
export const CLEAR_STATS = "CLEAR_STATS";

// STRATUM
export const GET_STRATUM_LIST = "GET_STRATUM_LIST";
export const STRATUM_REMOVED = "STRATUM_REMOVED";
export const RESET_STRATUM_STATUS = "RESET_STRATUM_STATUS";

// FIAT FORM
export const CLEAR_ERRORS_FIAT_FORM = "CLEAR_ERRORS_FIAT_FORM";

// SET BTC ADDRESS
export const SET_PAYMENT_ADDRESS = "SET_PAYMENT_ADDRESS";